import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import {MessagesProvider} from "@/utils/useMessage";
import MiddleLayout from "@/app/middleLayout";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <MiddleLayout>
    <body className={inter.className}>{children}</body>
    </MiddleLayout>
    </html>
  )
}
